README.md, gulpfile.js, ssi_to_jinja2.py
Additional build command 'gulp build-jinja' added to GULP.
This has been added because Data & Publications are run on CKAN which uses JINJA2 templating and is not compatible with SSI.
The build-jinja directive looks for the ./build/swe directory and searches every file for Apache SSI directives eg <!--#set and replaces them with the JINJA equivalent.
Build-jinja runs sequentially after a 5 second delay to allow wepack to complete so the build/swe directory exists.
@raymedia @AsifAmin
=> Converting SSI directives to JINJA2 for DATA and PUBLICATIONS

gulp/release-tasks/copy-element.js, gulp/release-tasks/ssi-to-static.js, gulpfile.js, src/assets/_project/_blocks/layout/content/options.html, src/docs/components.html, src/docs/index.html, src/docs/javascript.html, src/docs/layout.html, src/docs/qg-utilities.html, src/docs/styles.html
This isn't as elegant as I'd like, but it handles the docs properly.
Issue:
Assets for docs need to be root relative in build, but relative in release (to work on github.io).
Solution:
Run a conversion on release to change <link href="/assets/ to <link href="assets/ in docs files.
=> QOL-1036: Added build handler for relative styles in docs.

src/assets/_project/_blocks/components/forms/recaptcha.js, src/assets/_project/_blocks/data/qg-google-keys.json, src/assets/_project/_blocks/layout/content/_options.scss, src/assets/_project/_blocks/layout/content/options.html, src/assets/_project/_blocks/layout/footer/feedback-form.js, src/docs/captcha-footer-old.html, src/docs/captcha-footer-only.html, src/docs/captcha.html
Add missing footer feedback field which is required. 
Tweak recaptcha code to handle v2 and v3, add new v3 keys for footer feedback but still allow v2 when its not footer feed back on the page unless override options data-sitekey and or data-recaptcha-action is set on the form
based on https://github.com/qld-gov-au/squiz_theme/blob/ed8492032f677789e80cb3718f525656215e8076/assets/includes/global-remote/page-options-post.html for footer feedback
Also improvements which @andersmx  was working on in another project
=> QOL-6078 Update Footer feedback and Tweak reCAPTCHA code to handle v2 and v3,

.eslintrc, e2e/__tests__/components/alert-test.js, e2e/__tests__/components/call-out-box-test.js, src/assets/_project/_blocks/utils/qg-misc.js, src/docs/components/alerts.html, src/docs/components/call-out-box.html
- add tests in `alert` and `call-out-box` component to test the warning message if `i` element is used for FA icon
- add deprecation stories to doc to instruct consumers
- fix a minor eslint issue in vscode
=> Qol 8453 add tests on alert and call out box

src/assets/_project/_blocks/components/misc/_qg-images.scss, src/docs/components/images.html
- fix image icon size
- update doc for figure default having the `qg-fig` class
=> QOL-8574 update image icon style

src/assets/_project/_blocks/components/forms/_qg-forms.scss, src/assets/_project/_blocks/scss-general/_qg-variables.scss
Added a new class to encapsulate all the latest form styles
With the class '.qg-forms-v2' and the old #formio id, all forms.io will be updated directly, so no need to add any new class. However, when it comes to SWE forms, we need to add this new class '.qg-forms-v2' to get the latest styles. This will ensure that projects like Seniors and Food and Pantry are not broken.
=> Qol 8391 forms styles global

src/assets/_project/_blocks/layout/breadcrumbs/_breadcrumbs.scss
Also removed transition animation as not needed and requires a width to be set to work. See [https://css-tricks.com/using-css-transitions-auto-dimensions/](https://css-tricks.com/using-css-transitions-auto-dimensions/)
=> Removed max-width to allow long breadcrumbs to fill line space available

.storybook/main.js, package.json, src/assets/_project/_blocks/components/accordion/_qg-accordion.scss, src/assets/_project/_blocks/components/buttons/_qg-buttons.scss, src/stories/components/Accordion/Accordion.stories.mdx, src/stories/components/Accordion/templates/States.html, src/stories/components/Buttons/Buttons.stories.mdx, src/stories/components/Buttons/templates/States.html, src/stories/decorators/Grid.js, src/stories/decorators/index.js
Add example stories to show states of a component, so they different states of a component can be testable in visual testing.
- add storybook pseudo class plugin
- add `states` stories for Buttons and Accordion
- Modified Button class to show pseudo style (align to Bootstrap implementation)
- add `Grid` Storybook decorator
=> Add example stories to show states of a component

.storybook/main.js, package.json, src/assets/_project/_blocks/components/accordion/_qg-accordion.scss, src/assets/_project/_blocks/components/buttons/_qg-buttons.scss, src/stories/components/Accordion/Accordion.stories.mdx, src/stories/components/Accordion/templates/States.html, src/stories/components/Buttons/Buttons.stories.mdx, src/stories/components/Buttons/templates/States.html, src/stories/decorators/Grid.js, src/stories/decorators/index.js, src/stories/helpers/getMobileProps.js, src/stories/helpers/index.js, src/stories/layout/Breadcrumbs/Breadcrumbs.stories.mdx, src/stories/layout/Breadcrumbs/templates/BreadcrumbAgency.html, src/stories/layout/Breadcrumbs/templates/BreadcrumbGlobal.html, src/stories/layout/Footer/Footer.stories.mdx, src/stories/layout/Footer/templates/Footer.html, src/stories/layout/Header/Header.stories.mdx, src/stories/layout/Header/templates/Header.html, src/stories/templates/AggregationPage/AggregationPage.stories.mdx, src/stories/templates/ApplicationPage copy/ApplicationPage.stories.mdx, src/stories/templates/ContentPage/ContentPage.stories.mdx, src/stories/templates/ContentPageNoAsides/ContentPageNoAsides.stories.mdx, src/stories/templates/ContentPageWithoutLocation/ContentPageWithoutLocation.stories.mdx, src/stories/templates/IndexPage/IndexPage.stories.mdx, src/stories/templates/TopicIndexPage/TopicIndexPage.stories.mdx
Due to the size of this change, it break it up into the following parts:
Part 1 - install Storybook infrastructure
Part 2 - create stories for foundations (typography, color, etc.)
Part 3 - create stories for components - first batch
Part 4 - create stories for templates
Part 5 - integrate with Chromatic (trial)
major changes:
- replicate stories from [forgov templates doc](https://www.forgov.qld.gov.au/information-and-communication-technology/communication-and-publishing/website-and-digital-publishing/website-standards-guidelines-and-templates/swe/templates).
- add stories and helpers to display component in mobile view (also generate mobile view snapshot in visual testing).
- add SSI support to Storybook's Webpack settings so it can render existing HTML template directly.
=> Qol 9230 add storybook part4

gulpfile.babel.js, src/assets/_project/_blocks/layout/_pagemodels/_index.scss, src/assets/_project/_blocks/layout/breadcrumbs/breadcrumbs.js, src/assets/_project/_blocks/layout/content/_content.scss, src/assets/_project/_blocks/utils/qg-ajax-call.js, src/stories/components/Buttons/Buttons.stories.mdx, src/stories/components/Buttons/templates/Links.html
Same as the 'btn' and 'qg-btn' classes.
This should resolve eg the button text on /transport/boating/registration/recreational turning blue and the button background vanishing on focus.
=> [QOL-9431] exclude links with the 'button' class from the usual styling

src/assets/_project/_blocks/components/buttons/_qg-buttons.scss, src/assets/_project/_blocks/components/link/_qg-link.scss, src/assets/_project/_blocks/layout/content/_location-setter.scss, src/assets/_project/_blocks/layout/footer/_footer-feedback.scss, src/assets/_project/_blocks/scss-general/_qg-css-variables.scss, src/assets/_project/_blocks/scss-general/_qg-variables.scss, src/assets/_project/_blocks/scss-general/bootstrap/_variables.scss
Safari on iOS does not fully support the combined 'text-decoration' declaration, so for greater compatibility, it's best to split it into individual declarations, 'text-decoration-line', 'text-decoration-style', etc.
SASS mixins help to keep this DRY.
=> QOL-9431 Split text-decoration into individual declarations

src/assets/_project/_blocks/components/link/_qg-link.scss, src/assets/_project/_blocks/layout/_pagemodels/_aggregation.scss, src/assets/_project/_blocks/layout/_pagemodels/_index.scss, src/assets/_project/_blocks/layout/asides/_asides.scss, src/assets/_project/_blocks/layout/content/_content.scss
- Apply link styling to more page blocks (homepage has unusual structure).
- Restrict an index style rule so it doesn't prohibit hovered links from being underlined.
=> QOL-9431 Link styling fixes

src/assets/_project/_blocks/components/accordion/_qg-accordion.scss, src/assets/_project/_blocks/components/banners/_qg-promotional-banner.scss, src/assets/_project/_blocks/components/buttons/_qg-buttons.scss, src/assets/_project/_blocks/components/forms/_qg-forms.scss, src/assets/_project/_blocks/components/link/_qg-link.scss, src/assets/_project/_blocks/components/misc/_qg-images.scss, src/assets/_project/_blocks/components/quick-exit/_qg-quick-exit.scss, src/assets/_project/_blocks/components/site-search/qg-site-search.scss, src/assets/_project/_blocks/components/tables/_tables.scss, src/assets/_project/_blocks/layout/_print.scss, src/assets/_project/_blocks/layout/banners/_qg-banner-blurb.scss, src/assets/_project/_blocks/layout/content/_location-setter.scss, src/assets/_project/_blocks/layout/content/content-types/_cut-in-images.scss, src/assets/_project/_blocks/layout/content/content-types/_promotions.scss, src/assets/_project/_blocks/layout/footer/_footer-feedback.scss, src/assets/_project/_blocks/layout/footer/_service-centre.scss, src/assets/_project/_blocks/layout/footer/_site-footer.scss, src/assets/_project/_blocks/layout/header/_header-location.scss, src/assets/_project/_blocks/layout/header/_portal-links.scss, src/assets/_project/_blocks/layout/header/_site-nav.scss, src/assets/_project/_blocks/layout/header/_site-search.scss, src/assets/_project/_blocks/layout/header/_site-utilities.scss, src/assets/_project/_blocks/layout/section-nav/_section-nav.scss, src/assets/_project/_blocks/legacy/forms/_forms.scss, src/assets/_project/_blocks/legacy/forms/_old_forms.scss
Particularly refine underline styles to only use 'text-decoration-line' so it's easier for specific elements to customise other aspects (thickness, color).
=> [QOL-9431] split 'text-decoration' combined styles into individual declarations

src/assets/_project/_blocks/components/buttons/_qg-buttons.scss
- This makes it easier for the service finder buttons to use the correct colour despite a misapplied style
=> QOL-9431 fix service finder button colours on hover

src/assets/_project/_blocks/components/misc/_qg-cards.scss
- 100% width is now in a more specific block, which would make it override the thumbnail rule, so we need to specifically exclude thumbnails from it
=> [QOL-9431] preserve thumbnail image size

src/assets/_project/_blocks/layout/header/_site-search.scss
- Should be dark grey not pale grey
- This was introduced when 7e2c55aded1dfdce8ad94cc6e77806e9d7de433e deleted src/assets/_project/_blocks/scss-general/_qg-global-theme.scss
=> QOLDEV-47 fix global search text colour

src/assets/_project/_blocks/components/accordion/_qg-accordion.scss, src/assets/_project/_blocks/components/buttons/_qg-buttons.scss, src/assets/_project/_blocks/components/link/_qg-link.scss, src/assets/_project/_blocks/layout/footer/_service-centre.scss, src/assets/_project/_blocks/scss-general/_qg-variables.scss
Reapply all text-decoration directives so that internal elements don't override them.
=> QOLDEV-34 fix underline on hover for footer buttons

src/assets/_project/_blocks/components/buttons/_qg-buttons.scss
- Not just btn-global-primary and btn-global-secondary
=> [QOLDEV-34] set rounded corners for all qg-btn borders

src/assets/_project/_blocks/components/link/_qg-link.scss
- We want a single border around the whole element, not a separate border around each line.
=> [QOL-9265] fix link outline behaviour in Firefox to match Chrome

src/assets/_project/_blocks/layout/header/_coat-of-arms.scss
- Otherwise the outline has problems in Firefox
=> [QOL-9265] apply standard outline styles to logo link

src/assets/_project/_blocks/components/alerts/_qg-alert.scss
- Link underline should be offset 5px and increase thickness on hover/active/focus.
=> [QOLDEV-45] apply standard styling to alert links

src/assets/_project/_blocks/layout/header/_portal-links.scss, src/assets/_project/_blocks/layout/header/_site-nav.scss
On focus, mobile search menu items gain a 3px thickness outline with a 2px offset, so we need a 5px margin to fit it without the risk of crowding.
=> [QOLDEV-71] increase mobile menu margins to accommodate outline on focus

src/assets/_project/_blocks/components/buttons/_qg-buttons.scss, src/assets/_project/_blocks/components/link/_qg-link.scss, src/assets/_project/_blocks/legacy/forms/_forms.scss, src/stories/components/Buttons/templates/States.html
Apply similar styling to 'qg-btn' class.
This is needed for the TMR "Register a boat" button.
=> QOLDEV-34 fix styling for 'button' class links

src/assets/_project/_blocks/layout/section-nav/_section-nav.scss
Links need to have either 'display: block' or 'display: inline-block' to prevent a bug with multi-line outlines. Standard styling therefore applies 'inline-block'. However, when the links were previously 'display: block', this causes the clickable area to shrink. Fixed by setting width to 100%.
=> [QOLDEV-227] fix side nav buttons so the whole area is clickable

src/assets/_project/_blocks/components/link/_qg-link.scss, src/assets/_project/_blocks/layout/_pagemodels/_guide.scss, src/stories/components/Print/templates/PrintGuide.html
- Increase spacing above pagination links
- Don't add 'display: inline-block' to pagination links on focus
- Don't force link backgrounds to be transparent
=> QOLDEV-245 fix print guide styling

src/assets/_project/_blocks/components/link/_qg-link.scss, src/assets/_project/_blocks/legacy/forms/_forms.scss, src/assets/_project/_blocks/legacy/forms/_old_forms.scss, src/stories/components/Buttons/templates/Links.html
- Don't apply 'inline-block' styling to the Digital Dashboard graph headings since it interferes with existing 'block' styling
- Make 'More Information' links consistently white
=> QOLDEV-245 fix Digital Dashboard links

src/assets/_project/_blocks/layout/_typography.scss, src/assets/_project/_blocks/scss-general/bootstrap/_variables.scss
Current heading line-heights are based on the imported Bootstrap (3-ish) styles where default is 1.1 ([unitless](https://developer.mozilla.org/en-US/docs/Web/CSS/line-height#values)), except for h2 which has been customised to be 1.5rem.
As a fix to adjust the heading line heights to accommodate new hyperlink styles my pull request proposes to:
- Increase default line-height of headings to 1.3 (this will then apply to h1 and h2)
- Increase line-height of h3 and h4 to 1.4
- Increase line-height of h5 and h6 to 1.5
=> QOLDEV-260 heading line height fix

src/assets/_project/_blocks/components/link/_qg-link.scss, src/stories/components/Buttons/templates/States.html
- The button will handle the outline, we don't want to double up
=> [QOLDEV-250] skip focus/active outlines for links inside buttons

src/assets/_project/_blocks/layout/content/_content.scss
- Don't add list item spacing to 'select2' elements that are styled by JavaScript
=> [QOLDEV-262] fix margins for multi-select elements

src/assets/_project/_blocks/components/forms/_qg-forms.scss, src/assets/_project/_blocks/scss-general/_qg-variables.scss, src/stories/components/Forms/Forms.stories.mdx, src/stories/components/Forms/templates/CheckboxStates.html, src/stories/components/Forms/templates/RadioStates.html
Compare to designs on Figma: https://www.figma.com/file/5BrkUy62yKzGbRJnrUcLLM/Form-control-inputs%3A-Radio-and-checkbox?node-id=19%3A1893
- Use black checkmark on a white background regardless of browser defaults.
- Apply blue outline on focus.
=> QOLDEV-62 make checkbox styling consistent

src/assets/_project/_blocks/components/accordion/_qg-accordion.scss, src/assets/_project/_blocks/components/link/_qg-link.scss
Update accordion appearance according to new Figma designs
- Accordion links should be blue on hover, not black, with a thicker underline instead of none.
=> QOLDEV-223 accordion link styling

src/assets/_project/_blocks/components/forms/_qg-forms.scss, src/assets/_project/_blocks/components/link/_qg-link.scss, src/assets/_project/_blocks/components/misc/_qg-cards.scss, src/assets/_project/_blocks/layout/content/_content.scss, src/assets/_project/_blocks/scss-general/_qg-variables.scss
Replace box shadow with a standard outline, as per Figma designs.
=> QOLDEV-226 update card focus state

src/assets/_project/_blocks/components/misc/_qg-misc.scss
- Drop 'inline-block' styling so that the file metadata is the same height as the other text on Chrome/Safari, thus keeping the focus outline rectangular. This will have the undesired side effect that the underline will continue under the entire link.
=> [QOLDEV-222] fix outline on document download link focus

src/assets/_project/_blocks/components/link/_qg-link.scss
- On browsers that support the :has pseudo-selector, we can use it to transfer the text decoration from the 'u' tag to the link, allowing the underline to use the standard styling rules.
=> [QOLDEV-221] improve handling of links wrapped in 'u' tags

src/assets/_project/_blocks/components/buttons/_qg-buttons.scss, src/assets/_project/_blocks/components/link/_qg-link.scss, src/assets/_project/_blocks/components/misc/_qg-cards.scss, src/assets/_project/_blocks/scss-general/_qg-variables.scss, src/stories/helpers/getDecoratedParameters.js
Update the standard outline mixin to ensure that children of outlined elements will not apply extra outlines.
=> QOLDEV-268 Fix digital dashboard focus colour

src/assets/_project/_blocks/layout/_pagemodels/_guide.scss
- Safari seems to handle the flexbox configuration differently, resulting in the margin-top being too small and crowding the element above, so let's make it bigger.
=> [QOLDEV-245] increase spacing for print guide pagination

src/assets/_project/_blocks/components/link/_qg-link.scss, src/assets/_project/_blocks/scss-general/_qg-variables.scss, src/stories/components/Forms/templates/Validation.html
Don't apply a different underline offset to links inside form.io spans that will have an underline for the whole text.
=> QOLDEV-278 fix double underline in validation error box

src/assets/_project/_blocks/components/accordion/_qg-accordion.scss
- Use 'display: inline-block' to stop accordion headings from unnecessarily line-wrapping
=> [QOLDEV-223] fix accordion heading height

src/assets/_project/_blocks/components/site-search/qg-site-search.js
- Don't collapse the Concierge box too aggressively when components are clicked, since we need to allow clicking on search suggestions
=> [DC-33448][QOLCHG-87] fix global search suggestions being clicked

src/assets/_project/_blocks/components/site-search/qg-site-search.js
- We need to drop the binding to all header buttons, since the search suggestions are button elements
Previous pull request unfortunately didn't fix it, but I've now narrowed down exactly which selector caused the problem and why.
=> [DC-33448][QOLCHG-87] fix global search suggestions

src/assets/_project/_blocks/components/accordion/_qg-accordion.scss, src/assets/_project/_blocks/scss-general/_qg-variables.scss
- Use 'inline-block' regardless of image presence
=> [QOLDEV-223] fix height of accordion heading with image

src/docs/assets/css/ictdashboard.css
- Use 'display: inline-block' to stop tender links from generating spurious line breaks in Chrome
=> [QOLDEV-275] fix Digital Dashboard tender links on Chrome

src/assets/_project/_blocks/layout/_typography.scss, src/assets/_project/_blocks/scss-general/bootstrap/_variables.scss
It was noticed that for any h2 heading links in an aside that the underline weight change on hover was not entirely visible. Increasing h2 line-height to 1.4 addressed the problem.
Edit: Here's a screenshot example of what was happening:
=> QOLDEV-260 heading line height fix - h2 only

src/assets/_project/_blocks/scss-general/_qg-variables.scss
- Chrome makes the inner spans inherit from the link automatically, but Firefox does not, so we make it explicit
=> [QOLDEV-223] ensure accordions use thicker underline on hover

src/assets/_project/_blocks/layout/site-search-form.html, src/docs/examples/breadcrumb.html, src/docs/examples/cut-in.html, src/docs/examples/form-new-styles.html, src/docs/examples/formio.html, src/docs/examples/guide-page.html, src/docs/examples/index.html, src/docs/examples/recaptcha2.html, src/docs/examples/search-page.html, src/docs/examples/section-nav-example.html, src/docs/examples/service-finder.html, src/stories/components/Header/templates/Search.html
https://ssq-qol.atlassian.net/browse/QOLDEV-301
Derived from: https://ssq-qol.atlassian.net/browse/QOLSVC-433
Search inbox should not have aria-required=true as it is not a mandatory field.
=> QOLDEV-301 Removing aria-required from search input

src/assets/_project/_blocks/layout/banners/_qg-banner-blurb.scss
**Internal ticket reference**: [https://ssq-qol.atlassian.net/browse/QOLDEV-164](https://ssq-qol.atlassian.net/browse/QOLDEV-164)
**WCAG 2.1 technique reference**: [https://www.w3.org/WAI/WCAG21/Techniques/general/G18](https://www.w3.org/WAI/WCAG21/Techniques/general/G18)
**Tools** I used for checking contrast of text colour on a background image:
- [Optimal Overlay Finder - Readable Text on a Background Image](https://codepen.io/yaphi1/live/oNbEqGV )
- [A11y accessibility check for text colour on background image](http://www.brandwood.com/a11y/ )
[This article](https://css-tricks.com/nailing-the-perfect-contrast-between-light-text-and-a-background-image/) found that for the common case of white text on a black transparent overlay, you’ll never need an opacity over 0.54 to achieve WCAG …
=>  QOLDEV-164 Adjusted opacity value of banner blurb background for better contrast with text

src/assets/_project/_blocks/components/link/_qg-link.scss, src/assets/_project/_blocks/layout/section-nav/_section-nav.scss, src/assets/_project/_blocks/scss-general/_qg-variables.scss
https://oss-uat.clients.squiz.net//health/services/travel/subsidies/ptss-subsidies
Based on https://www.figma.com/file/veO6GlWUx6rVmMeo9vPECS/SWE-UI-kit?node-id=4137-8713 grey background for the side nav items only should occur on hover, and not active.
This completes https://ssq-qol.atlassian.net/browse/QOLDEV-199
Print link was missing the blue outline when focused. It should not be underlined though.
https://ssq-qol.atlassian.net/browse/QOLDEV-321
=> Qoldev 321 print button and hover state

src/assets/_project/_blocks/components/accordion/_qg-accordion.scss, src/assets/_project/_blocks/components/link/_qg-link.scss, src/assets/_project/_blocks/layout/header/_site-nav.scss, src/assets/_project/_blocks/scss-general/_qg-variables.scss
https://ssq-qol.atlassian.net/browse/QOLDEV-314
https://oss-uat.clients.squiz.net/health/services/travel/subsidies/ptss-subsidies
- Introducing #00B4FF as $qg-active-outline-brighter for darker backgrounds
- Introducing a second argument to `qg-button-outline-decoration` mixin called `$light-background`, so when the background is light, the outline color will be` $qg-active-outline`(#0096d6), if the background color is darker like the nav bar, the outline color will be `qg-active-outline-brighter`(#00b4ff).
- Removing border-radius on the outline so it looks square consistent with other link outlines.
- Updating nav-link padding to center the word in the outline
- This also fixes the missing underline on Print link (confirmed with Bec that it is needed)
- Also fixes the missing underline …
=> QOLDEV-314 Updating the outline on main nav items

src/assets/_project/_blocks/components/link/_qg-link.scss, src/assets/_project/_blocks/layout/header/_coat-of-arms.scss
https://ssq-qol.atlassian.net/browse/QOLDEV-331
Brightening the outline color for the logo to be consistent with the nav items.
Before:
After:
=> Qoldev 331 logo outline

src/assets/_project/_blocks/layout/header/access.html, src/assets/_project/_blocks/layout/header/header-without-location.html, src/assets/_project/_blocks/layout/header/header.html, src/assets/_project/_blocks/layout/header/portal-links.html, src/assets/_project/_blocks/layout/header/site-nav.html, src/docs/examples/breadcrumb.html, src/docs/examples/cut-in.html, src/docs/examples/form-new-styles.html, src/docs/examples/formio.html, src/docs/examples/guide-page.html, src/docs/examples/index.html, src/docs/examples/recaptcha2.html, src/docs/examples/search-page.html, src/docs/examples/section-nav-example.html, src/docs/examples/service-finder.html
https://ssq-qol.atlassian.net/browse/QOLDEV-328
Changes required to the landmarks:
- Adding role=”banner” to <head> tag
- Updating aria-label=”Main navigation” to aria-label=”main” as it would read as 'Main navigation navigation' by screen readers. (id="qg-site-nav")
- Adding aria-label=”top” to the <nav> tag (id="qg-portal-links")
- Removing role='navigation' from Skip to main (id="qg-access")
=> QOLDEV-328 Improving landmarks for a11y

src/assets/_project/_blocks/components/buttons/_qg-buttons.scss, src/assets/_project/_blocks/scss-general/_qg-variables.scss
https://ssq-qol.atlassian.net/browse/QOLDEV-34
From Bec:
Focus state - looks like it’s still inheriting a box-shadow from Bootstrap styles.
Focus and active state – Text should be underlined. Also, can the outline have rounded corners to match the button?
https://oss-uat.clients.squiz.net/forgov-dev/information-and-communication-technology/communication-and-publishing/website-and-digital-publishing/website-standards-guidelines-and-templates/swe/components/buttons#primary
=> QOLDEV-34 Improving primary button focus state

src/assets/_project/_blocks/layout/header/_coat-of-arms.scss
https://ssq-qol.atlassian.net/browse/QOLDEV-322
Safari before:
FireFox before:
After:
=> QOLDEV-322 Fixing logo outline in FF and Safari

src/assets/_project/_blocks/components/buttons/_qg-buttons.scss, src/assets/_project/_blocks/scss-general/_qg-variables.scss
https://ssq-qol.atlassian.net/browse/QOLDEV-34
It was working as expected when focus only and active only.
However when it is  focused and active together, the box-shadow appears. This change is to overwrite bootstrap's box-shadow value.
https://oss-uat.clients.squiz.net/forgov-dev/information-and-communication-technology/communication-and-publishing/website-and-digital-publishing/website-standards-guidelines-and-templates/swe/components/buttons
=> QOLDEV-34 Removing box-shadow for focus and active states together

src/assets/_project/_blocks/components/buttons/_qg-buttons.scss
- Fixing the text color for .btn-link.light
- Making tertiary button's outline with border-radius: 4px instead of 0
https://oss-uat.clients.squiz.net/forgov-dev/information-and-communication-technology/communication-and-publishing/website-and-digital-publishing/website-standards-guidelines-and-templates/swe/components/buttons
=> Qoldev 37 tertiary btn improvement

src/assets/_project/_blocks/components/link/_qg-link.scss, src/assets/_project/_blocks/layout/_pagemodels/_index.scss
Topic index page. Example: https://www.qld.gov.au/disability/adults
Franchise landing page. Example: [People with disability](https://www.qld.gov.au/disability)
https://ssq-qol.atlassian.net/browse/QOLDEV-206
- Removing underline from header and links in default state in screen sizes wider than 767px
- Fixing the hover and active state in mobile view by introducing ssero margin to the acording mixins
**Before:**
**After:**
**Before:**
**After:**
=> QOLDEV-206 Fixes on index and franchise landing pages

.storybook/previewMainTemplate.ejs, src/assets/_project/_blocks/layout/head-assets.html, src/docs/examples/cut-in.html, src/docs/examples/formio.html, src/docs/examples/index.html, src/docs/examples/search-page.html, src/docs/examples/service-finder.html
Removing max and min scale from the viewport.
https://webhint.io/docs/user-guide/hints/hint-meta-viewport/?source=devtools
_These properties can block the user from zooming on a page. With such a wide range of devices available with different display dimensions, screen resolutions, pixel densities, etc., it is difficult to choose an appropriate text size in a design. Most of the time using these properties enable users to pick a text size that is unreadable while preventing them from zooming, frustrating them, or making the web site/app inaccessible in some cases._
=> QOLDEV-302 Removing maximum and minimum scale from viewport

src/assets/_project/_blocks/components/buttons/_qg-buttons.scss
This change would make buttons that don't have qg-btn class to inherit SWE styles.
Example: The submit button on https://oss-uat.clients.squiz.net/contact-us
=> QOLDEV-34 Generalising all buttons states

src/assets/_project/_blocks/components/forms/_qg-forms.scss, src/assets/_project/_blocks/components/link/_qg-link.scss, src/assets/_project/_blocks/scss-general/_qg-variables.scss, src/stories/components/Forms/templates/Validation.html
https://ssq-qol.atlassian.net/browse/QOLDEV-343
https://oss-uat.clients.squiz.net/contact-us
When you submit contact us form without the required fields:
Form io also needs to be updated to remove role='link' from the span. Otherwise the underline will be still there.
=> Qoldev 343 Styling underline in alert danger

src/assets/_project/_blocks/layout/_pagemodels/_index.scss
https://oss-uat.clients.squiz.net/disability
Removing underline from the item headers in mobile view as well as desktop based on the new requirements. So they look like buttons:
=> QOLDEV-206 Index page, no underline for all sreen sizes

src/assets/_project/_blocks/components/print/qg-print.scss
https://ssq-qol.atlassian.net/browse/QOLDEV-321
https://oss-uat.clients.squiz.net/health/services/travel/subsidies/ptss-subsidies
https://oss-uat.clients.squiz.net//environment/water/residence/use/waterwise-at-work
Lakshmi asked to add some padding below the print link so the print outline doesn't overlap the image on https://oss-uat.clients.squiz.net/health/services/travel/subsidies/ptss-subsidies.
**After:**
=> Qoldev 321 print button bottom padding

src/assets/_project/_blocks/components/site-search/qg-site-search.js, src/assets/_project/_blocks/layout/site-search-form.html, src/docs/examples/breadcrumb.html, src/docs/examples/cut-in.html, src/docs/examples/form-new-styles.html, src/docs/examples/formio.html, src/docs/examples/guide-page.html, src/docs/examples/index.html, src/docs/examples/recaptcha2.html, src/docs/examples/search-page.html, src/docs/examples/section-nav-example.html, src/docs/examples/service-finder.html, src/stories/components/Header/templates/Search.html
https://ssq-qol.atlassian.net/browse/QOLDEV-301
I found a valid example of a searchob with suggesting keywords on bootstrap website: https://getbootstrap.com/docs/4.3/components/
It has aria-expanded attribute which toggles accordingly. This PR is to implement toggling aria-expanded on the searchbox.
We need to add role='combobox' to the <input>, otherwise the screenreaders won't announce the input box expandable.
The same change should go to Squiz to the related asset Id.
=> QOLDEV-301 Handling aria-expanded on the searchbox

src/assets/_project/_blocks/components/misc/_qg-cards.scss
Adding box-shadow for clickable cards in default state only.
Example:
https://oss-uat.clients.squiz.net/forgov-dev/information-and-communication-technology/communication-and-publishing/website-and-digital-publishing/website-standards-guidelines-and-templates/swe/components/cards
https://oss-uat.clients.squiz.net/jobs/jobs-and-training-support
=> Qoldev 226 improving card default state

src/assets/_project/_blocks/layout/banners/_qg-banner-blurb.scss
https://oss-uat.clients.squiz.net/health/conditions/health-alerts/coronavirus-covid-19
Desktop: link color should be white
Mobile: link color as standard
=> Qoldev 44 blurb text color

src/assets/_project/_blocks/components/link/_qg-link.scss, src/assets/_project/_blocks/layout/banners/_qg-banner-blurb.scss, src/assets/_project/_blocks/scss-general/_qg-variables.scss
This fix is to make both the blurb on https://oss-uat.clients.squiz.net/health/conditions/health-alerts/coronavirus-covid-19 and the dropdwn on the search box on https://oss-uat.clients.squiz.net/services work as expected in desktop and mobile view. The first one has white text in desktop view, the second one has black text in all screens.
Previously the link in the dropdown were all white.
Also the links within the dropdown in services searchbox did not have the SWE hyperlink style, like the underline offset. This is now fixed.
=> QOLDEV-44 Text color on services dropdown, applying standard hyperlinks rules

src/assets/_project/_blocks/components/site-search/qg-site-search.scss, src/assets/_project/_blocks/layout/banners/_qg-banner-blurb.scss
Adjusting search button on the search result page:
https://oss-uat.clients.squiz.net/search?query=&num_ranks=10&tiers=off&collection=qld-gov&profile=qld
Before:
After:
Also fixing the padding for immediate links within qg-search-concierge-content
Also had a chat with Bec and Amit. Ideally we need to review the search boxes in the system and make them consistent. There is no up-to-date Figma file with all the interaction states. So we limit the changes for now.
=> Qoldev 336 global searchbox improvement

gulpfile.babel.js
Adding argv as a second argument to cdn-branch task. This would fix the error branch not found when running:
npm run publish-test-cdn
=> QOLDEV-359 cdn release fix

src/assets/_project/_blocks/components/misc/_qg-cards.scss
Homepage
https://oss-uat.clients.squiz.net/
This bug comes from the default 2px margin applied to all links around the system. This type of card is not one of our standard card defined in the document. It is done by the franchise.
I could also could do:
However I thought the code committed is safer and only impacts feature-section class.
=> Qoldev 379 franchise cards

gulp/publish-tasks/git.js, gulpfile.babel.js
**argv.branch bug fix**
Fixes "undefined" bug on argv.branch variable.  Update git.js BRANCH() and PUSH() functions to test for property.
**SSH Flag**
Add a "SSH" flag to the git.js COMMIT() function, which allows calling functions to optionally specify an SSH protocol instead of HTTPS.  Used when switching between internal and network publishing routes.
=> QOLDEV-359 cdn release fix branchnames

src/assets/_project/_blocks/layout/footer/_footer-feedback.scss
Fixing the outline for feedback button in the footer
Before:
After:
=> QOLDEV-356 Focused state for footer feedback button

e2e/__tests__/components/call-out-box-test.js, src/assets/_project/_blocks/components/buttons/_qg-buttons.scss, src/assets/_project/_blocks/layout/banners/_qg-banner-blurb.scss
https://oss-uat.clients.squiz.net/jobs/graduate-portal
Fixing the style of the buttons are made with <a> tag.
Before:
After:
Also buttons on service finder don't need the white link mixin. Default sate should not be underlined.
=> Qoldev 44 services blurb text color

src/assets/_project/_blocks/components/link/_qg-link.scss, src/assets/_project/_blocks/components/quick-exit/_qg-quick-exit.scss, src/assets/_project/_blocks/franchise/DFV/qg-dfv.scss, src/assets/_project/_blocks/qg-main.scss, src/assets/_project/_blocks/scss-general/_qg-variables.scss, src/assets/_project/_blocks/scss-general/bootstrap/_bridge_bootstrap3.scss
https://oss-uat.clients.squiz.net/community/getting-support-health-social-issue/support-victims-abuse/domestic-family-violence/what-is-domestic-and-family-violence/what-are-the-patterns-of-domestic-violence/about-domestic-and-family-violence-and-coercive-control
https://oss-uat.clients.squiz.net/community/getting-support-health-social-issue/support-victims-abuse/domestic-family-violence/what-is-domestic-and-family-violence/what-are-the-patterns-of-domestic-violence
This change is to keep the color of the visited links in DFV unchanged for the user's safety reason.
Also #more-information block at the bottom of first link and Back button on the top left corner of DFV subpages were missing the standard SWE link and button styles. They now have.
Not all DFV pages have the class .dvf-content. …
=> Qoldev 412 dfv visited links

src/assets/_project/_blocks/components/print/qg-print.scss, src/assets/_project/_blocks/layout/footer/_site-footer.scss
Removing fixed height from page options to remove the vertical space added to all pages.
Example:
without page options: https://oss-uat.clients.squiz.net/transport
with page options: https://uat.forgov.qld.gov.au/information-and-communication-technology/qgea-policies-standards-and-guidelines/principles-for-the-use-of-service-delivery-channels
Also excluding white link from the form inside the feedback form.
=> Qoldev 416 top margin for pages

src/assets/_project/_blocks/components/print/qg-print.scss, src/assets/_project/_blocks/layout/section-nav/_mobile_step_nav.scss
After talking to Bec and Manjeet, page options is updated to avoid the impact on the vertical spacing at the top of the pages.
Examples:
https://uat.forgov.qld.gov.au/information-and-communication-technology/qgea-policies-standards-and-guidelines/principles-for-the-use-of-service-delivery-channels
https://oss-uat.clients.squiz.net/environment/plants-animals/wildlife-permits/permit-types/recreational
Also fixing an obvious a11y bug on the second link.
Before:
After:
=> QOLDEV-321 Making print link absolute

src/assets/_project/_blocks/scss-general/bootstrap/_bridge_bootstrap3.scss
https://ssq-qol.atlassian.net/browse/QOLDEV-430
This is to remove the visited link styles from unwanted spots like menu items, search suggestions, header links.
The visited link style is already covered by qg-link-visited-decoration mixin when needed.
This branch is deployed to UAT for the time being.
Before:
=> QOLDEV-430 Removing visited links style from _bridge-bootstrap3

src/assets/_project/_blocks/components/carousel/_qg-carousel.scss
New 0px margins applied to carousel control buttons to overcome an inherited 2px margin that was added to a global scope.
!important tag used due to very narrow scope of this carousel control class.
=> QOLDEV 67 carousel margins new PR

src/assets/_project/_blocks/components/accordion/_qg-accordion.scss
A _button:hover > a_ state was required to replicate the behaviour of a direct a:hover state.
Button hovers should apply to full width (and height) of accordion headings.
=> QOLDEV-428 accordion button hover state hotfix

src/assets/_project/_blocks/components/alerts/_qg-alert.scss
https://oss-uat.clients.squiz.net/jobs/jobs-and-training-support/help-starting/help-looking-for-work
Link should not change color when visited or hovered. Underline thickness should change when hovered.
UAT is updated with this change.
Expected hover state:
=> Qoldev 427 links within alerts

src/assets/_project/_blocks/utils/qg-misc.js
Fix for internal vertical alignment, and footer placement, of equal height cards
This change refactors the equal card height setHeight() function.
- Switch from jQuery to vanilla JS
- Update incorrect class references from .cards__equal-height to .qg-cards__equal-height
- Iterates multiple card-block sections (when there are more than one on the same page)
=> QOLDEV 434 equal card heights js

package.json, src/assets/_project/_blocks/components/accordion/_qg-accordion.scss, src/assets/_project/_blocks/components/alerts/_qg-alert.scss, src/assets/_project/_blocks/components/carousel/_qg-carousel.scss, src/assets/_project/_blocks/layout/breadcrumbs/_breadcrumbs.scss, src/assets/_project/_blocks/scss-general/bootstrap/_bridge_bootstrap3.scss, src/assets/_project/_blocks/utils/qg-misc.js
=> Release v4.2.2

src/assets/_project/_blocks/components/misc/_qg-images.scss
- removing important from max-width for figure to able to override it via the new full-width configuration in image content container template (asset 821)
- defining max-width-none class to be used in image cct when it is configured to be full-width
=> QOLDEV-74 Improving <figure> styles

src/assets/_project/_blocks/components/print/qg-print.scss, src/docs/components/print.html, src/docs/examples/cut-in.html, src/docs/examples/form-new-styles.html, src/docs/examples/formio.html, src/docs/examples/guide-page.html, src/docs/examples/recaptcha2.html, src/docs/examples/section-nav-example.html, src/stories/components/Print/templates/Default.html, src/stories/components/Print/templates/PrintGuide.html
The extra space is removed from the global paint layout #118410 in UAT as well.
Before:
https://www.qld.gov.au/disability/children-young-people/bullying/bullying-disability-mental-health
After:
https://oss-uat.clients.squiz.net/disability/children-young-people/bullying/bullying-disability-mental-health
=> Qoldev 403 print icon

src/assets/_project/_blocks/layout/banners/_qg-banner-blurb.scss
It was only working for links that directly come after .blurb class. In example below link is inside p.
Before:
After:
=> QOLDEV-352 Applying dark theme colors (white) to the links within banner

src/docs/examples/breadcrumb.html, src/docs/examples/cut-in.html, src/docs/examples/form-new-styles.html, src/docs/examples/formio.html, src/docs/examples/guide-page.html, src/docs/examples/index.html, src/docs/examples/recaptcha2.html, src/docs/examples/search-page.html, src/docs/examples/section-nav-example.html, src/docs/examples/service-finder.html
https://getbootstrap.com/docs/5.0/utilities/display/#display-in-print
Replacing no-print with Bootstrap d-print-none which is available in Bootstrap 4 and 5.
d-print-none is going to be added in the global page layout to hide page options containing forgov subscrive link.
https://uat.forgov.qld.gov.au/information-and-communication-technology/qgea-policies-standards-and-guidelines/principles-for-the-use-of-service-delivery-channels#
**Before:**
**After:**
=> QOLDEV-443 Replacing no-print with bootstrap d-print-none

src/assets/_project/_blocks/components/link/_qg-link.scss, src/assets/_project/_blocks/franchise/DFV/qg-dfv.scss, src/assets/_project/_blocks/layout/content/_content.scss
Applying button styles to Dfv portal
This includes default, active, hover states. Also the vertical spacing in the link list is fixed as well.
https://oss-uat.clients.squiz.net/community/getting-support-health-social-issue/support-victims-abuse/domestic-family-violence/i-want-to-help-someone
**Before:**
**After:**
**Before:**
**After:**
=> Qoldev 77 hyperlinks on dfv

src/stories/components/Images/templates/WithoutBorder.html
https://qld-gov-au.github.io/qg-web-template/?path=/story/components-images--without-border
**Before:**
**After:**
=> QOLDEV-74 Using the correct class for images without border

src/assets/_project/_blocks/components/alerts/_qg-alert.scss
Buttons within alertboxes should not have underline in default state
https://oss-uat.clients.squiz.net/housing/buying-owning-home/financial-help-concessions/resilient-homes-fund
=> QOLDEV-450 Styling the buttons within alertbox

src/assets/_project/_blocks/components/misc/_qg-cards.scss
https://uat.forgov.qld.gov.au/information-and-communication-technology/communication-and-publishing/website-and-digital-publishing/website-standards-guidelines-and-templates/swe/components/cards#content_container_250117
The top border is removed from the card footer to save some space.
**Before:**
**After:**
=> QOLDEV-458 Removing top borderfram the card's footer

src/assets/_project/_blocks/utils/qg-datepicker.js, src/stories/components/Forms/templates/DatePicker.html
https://uat.forgov.qld.gov.au/information-and-communication-technology/communication-and-publishing/website-and-digital-publishing/website-standards-guidelines-and-templates/swe/components/forms#date
The date picker using qg-date-input was missing the date placeholder and also when you click on the input, the calendar wouldn't open.
The the jquery syntax was not right. $('input[class=\'qg-date-input\']').length is always 0. It was missing an asterisk. 
**Before:**
**After:**
=> QOLDEV-422 Fixing qg-date-input

src/assets/_project/_blocks/layout/footer/footer-legals.html
Replacing `no-print` with bootstrap `d-print-none`. A few instances were missed.
=> QOLDEV-443 Replacing no-print with d-print-none

src/assets/_project/_blocks/components/tables/_tables.scss, src/stories/components/Table/Table.stories.mdx, src/stories/components/Table/templates/NoStripe.html
https://uat.forgov.qld.gov.au/information-and-communication-technology/communication-and-publishing/website-and-digital-publishing/website-standards-guidelines-and-templates/swe/components/table
https://oss-uat.clients.squiz.net/dev/ghazal/test-table
SWE tables are striped by default.
This change was originated from a service request to add a SWE class to remove tiger stripes from the tables and also making them bordered at the same time for visibility.
Class qg-table-no-striped is defined to do that. Also I made <table> to inherit bootstrap `table `class. This makes the tables full-width.
**Before:**
**After:**
The same result is possible by adding customised classes in [global design customisation](https://oss-uat.clients.squiz.net/_admin/?screen=styles&assetid=118372) to apply …
=> Qoldev 73 striped tables

src/assets/_project/_blocks/components/misc/_qg-images.scss
Applying zero margin to the a[data-fancybox] within qg-fig.
https://uat.forgov.qld.gov.au/information-and-communication-technology/communication-and-publishing/website-and-digital-publishing/website-standards-guidelines-and-templates/swe/components/images#larger
https://oss-uat.clients.squiz.net/environment/management/environmental/offsets/what-when
**Before:**
=> QOLDEV-74 Applying default zero margin for the image link inside qg-fig

src/assets/_project/_blocks/layout/_print.scss
`no-print `class used to exist in SWE. Adding it back in order to make print work as expected just in case it is used anywhere in the Squiz content.
=> QOLDEV-443 Defining no-print class just in case it is used in Squiz content

e2e/__tests__/components/call-out-box-test.js, src/docs/components/call-out-box.html
https://oss-uat.clients.squiz.net/_resources/matrix-documentation/components/callout/_admin/?screen=contents&assetid=140042
[Callout](https://www.forgov.qld.gov.au/information-and-communication-technology/communication-and-publishing/website-and-digital-publishing/website-standards-guidelines-and-templates/swe/components/callout) 
Based on callout-box-test.js in SWE < i > before font awesome icon needs to be replaced by <span>.
This causes test to fail.
This needs to be be fixed both in Callout in Squiz #140042 and SWE documentations.
=> QOLDEV-501 Resolving callout chromatic test regarding icon

src/assets/_project/_blocks/components/misc/qg-document-links.js
This function looks for file summary strings on a page and reformats values for consistency and readability.
It is an update a previous SWE function with the same behaviour, but been converted from jQuery to vanilla JS and now rounds up file size values. The previous function stripped all values after the decimal point.
1. looks for this file summary pattern: for example "(PDF, 1.3 MB) or (DOCX 23.5KB)" on all links (A tags) in the DOM
2. checks the HREF of the link ends in .PDF, .RTF etc
3. reformats the file summary for consistency (PDF 517 KB)
4. Rounds UP the file size value to the nearest whole integer
5. Assumes a bias for over inflated sizes. e.g. 1.3 MB will round up to 2 MB
Original behaviour
(PDF 1.9 MB) was reformatted to (PDF 1 MB)
New behaviour
(PDF 1.9 MB) is reformatted to …
=> QOLDEV 386 fix filesummary js function

e2e/__tests__/components/funnelback-search-test.js, e2e/__tests__/layout/footer-feedback-test.js, package.json, src/assets/_project/_blocks/components/site-search/qg-site-search.js, src/assets/_project/_blocks/layout/footer/_service-centre.scss, src/assets/_project/_blocks/layout/location/qg-location.js, src/assets/_project/_blocks/layout/service-centre/service-centre.html, src/assets/_project/_blocks/layout/site-search-form.html, src/stories/components/Header/templates/Search.html
Version 4.2.3 will be released before 4.3.0 for Funnelback upgrade.
- Set your location in the footer https://oss-uat.clients.squiz.net/services
Squiz will be working on missing kmFromOrigin. When fixed it will appear in the footer as well.
- Also updating Search story file with the new search domain and collection string.
- footer-feedback-test.js needed to get updated to resolve test failure. This was done in 4.3.0.
- puppeteer version had to increase to resolve another build error. This was done in 4.3.0 as well.
=> Qoldev 515 funnelack upgrade set location

e2e/__tests__/components/funnelback-search-test.js, src/assets/_project/_blocks/components/alerts/_qg-alert.scss
This change was already reviewed and merged via https://github.com/qld-gov-au/qg-web-template/pull/989
I checked the branch QOLDEV-450-button-within-alertbox does not exist anymore and the code is missing from 4.3.0.
I created a new feature branch for it.
Also had to update funnelback search as the search results dynamically and the result strings won't be exactly the same over time. So changed to check the count of them which will be always 3 under suggestions.
=> QOLDEV-450 Styling buttons within the alertbox

src/assets/_project/_blocks/layout/content/_options.scss
https://oss-uat.clients.squiz.net/housing/buying-owning-home/financial-help-concessions/resilient-homes-fund
Aligning social media icon outlines to fix in FireFox and Safari.
**Before:**
=> QOLDEV-553 Styling social media links

package-lock.json, package.json
Upgrading puppeteer version to 21.1.0. This is done to avoid merge conflict with develop.
=> Puppeteer upgrade to 21.1.0

src/assets/_project/_blocks/components/accordion/_qg-accordion.scss, src/assets/_project/_blocks/components/link/_qg-link.scss
https://oss-uat.clients.squiz.net/contact-us/complaints-process
Removing in unnecessary space in accordion multi-line header for screens ~485px and below.
**Before:**
**After:**
=> QOLDEV-533 Removing unnecessary space in accordion

src/assets/_project/_blocks/components/tables/_tables.scss
NoStripe tables should be excluded from this css rule as well. Because they are bordered.
https://uat.forgov.qld.gov.au/information-and-communication-technology/communication-and-publishing/website-and-digital-publishing/website-standards-guidelines-and-templates/swe/components/table/_nocache
=> QOLDEV-592 Excluding NoStripe tables from border: 0

package.json, src/assets/_project/_blocks/components/tables/_tables.scss, src/assets/_project/_blocks/utils/qg-datatables.js, src/assets/_project/_blocks/utils/qg-util.js
https://oss-uat.clients.squiz.net/_resources/matrix-documentation/components/searchable-and-sortable-table
The button templates is added by dataTable jquery. I added some js code to add class qg-btn to the button in order to inherit SWE button styles. Also improved code syntax to some extent.
=> Qoldev 569 searchable table

src/assets/_project/_blocks/components/tables/_tables.scss
Bootstrap class `table-sm` was not working when applied in WYSIWYG editors. Taking `table { ..} `out of `#qg-primary-content` made the classes work as expected.
Adding table-sm class to existing tables on:
https://oss-uat.clients.squiz.net/dev/ghazal/test-table/_nocache
https://uat.forgov.qld.gov.au/information-and-communication-technology/communication-and-publishing/website-and-digital-publishing/website-standards-guidelines-and-templates/swe/components/table
=> QOLDEV-620 Making table-sm bootstrap class working in SWE

src/stories/components/Accordion/Accordion.stories.mdx, src/stories/components/Footer/Footer.stories.mdx, src/stories/components/Header/Header.stories.mdx, src/stories/templates/AggregationPage/ApplicationPage.stories.mdx, src/stories/templates/ContentPage/ContentPage.stories.mdx, src/stories/templates/ContentPageNoAsides/ContentPageNoAsides.stories.mdx, src/stories/templates/ContentPageWithoutLocation/ContentPageWithoutLocation.stories.mdx, src/stories/templates/IndexPage/IndexPage.stories.mdx, src/stories/templates/TopicIndexPage/TopicIndexPage.stories.mdx
Source code toggle buttons for mobile stories are not working. It is set to sourceState=”none”. It was supposed to not display the source code.
Example:
https://qld-gov-au.github.io/qg-web-template/?path=/docs/components-accordion--docs
https://qld-gov-au.github.io/qg-web-template/?path=/docs/components-header--docs
Also applying height to search story.
=> QOLDEV-577 Removing source code toggle button for mobile stories

src/assets/_project/_blocks/layout/banners/_qg-banner-blurb.scss
Fixing the default state for the button within service finder dropdown when you search for a term like 'registration'.
Also fixing the padding for the immediate link 'Browse all categories'
=> Qoldev 618 service finder button

src/assets/_project/_blocks/components/forms/_qg-forms.scss
Adds a new CSS hotfix to support Multifile Upload component when in error state.
=> QOLDEV-679 new CSS rule to support the Form IO Multifile upload component

src/assets/_project/_blocks/components/tables/_tables.scss, src/assets/_project/_blocks/utils/qg-datatables.js
This is to resolve below warning on searchable table in storybook:
Before:
After:
=> Qoldev 569 searchable table resolving warning

src/assets/_project/_blocks/layout/_pagemodels/_index.scss
Updating the breakpoint on topic and franchise pages
Also made the card-look index items to wrap into two column in md size screens
**Franchise landing page:** https://oss-uat.clients.squiz.net/transport/transport/_nocache
**Topic index page:** https://oss-uat.clients.squiz.net/transport/registration/_nocache
**768-991 px:**
**< 768px:**
=> Qoldev 668 changing breakpoint for topic index pages

src/assets/_project/_blocks/components/forms/_qg-forms.scss, src/assets/_project/_blocks/layout/_pagemodels/_index.scss
Vertical spacing between the index items used to be 50px. Decreasing it to 35px.
This came out of SWE UAT and recommended by Bec.
=> Decreasing vertical spacing between index items

src/assets/_project/_blocks/components/forms/_qg-forms.scss
Hotfix for a visual bug in SWE, where white text displays on white background in FormIO dropdown. Occurs when dropdown has a formio-error-wrapper class.
This fix is a permanent replacement in SWE for a temporary hotfix applied directly to Squiz under CHG-444.
Tested on UAT under web-template-release branch v4.4.0-test
=> QOLDEV-694 HOTFIX: update FormIO CSS in SWE to fix formIO error state

src/assets/_project/_blocks/components/forms/_qg-forms.scss, src/docs/assets/css/ictdashboard.css, src/stories/franchises/digital-dashboard/templates/Projects.html
Applying the fix height only to form.io drop downs without impacting other elements.
Also removed 'datatable' class from digital dashborad project table as it caused errors on the page. It is not a searchable table on the live site: https://www.qld.gov.au/digitalprojectsdashboard/projects
=> QOLDEV-666 Styling dropdowns
