qld-gov-au/qg-web-template

src/assets/js/sections/helpers.js, src/assets/js/sections/nav/mobile-nav.js
=> added global helpers

gulp-tasks/build-process/content.js, gulp-tasks/build-process/otherAssets.js, gulp-tasks/build-process/scripts.js, gulp-tasks/build-process/scss.js, src/assets/js/main.js, src/swe/examples/standard-page.html
=> build system updates

build/swe/examples/dynamic-loading-templates.html, src/swe/examples/dynamic-loading-templates.html
This page uses a very simple delayed loading plugin to demonstrate what happens when templates load after the javascript
=> EP: Add an example page demonstrating asynchronous loading issue

src/assets/includes/global/page-options-post.html, src/assets/includes/site-footer/footer-scripts.html, src/assets/js/components/feedback-form.js, src/assets/js/main.js, src/cue/examples/cue-example.html, src/swe/examples/example-page.html
- replace hidden inputs
- show example on swe & cue example pages.
- remove unused ssi variables from swe/cue example pages.
=> Use javascript rather than SSI for the feedback form context

src/assets/includes/breadcrumbs/breadcrumb-demo.html, src/assets/includes/global/page-options-post.html, src/assets/includes/site-header/site-navigation.html, src/assets/includes/site-header/site-utilities.html, src/assets/sass/page-content/DELETE_page-feedback.scss, src/assets/sass/page-content/_feedback.scss, src/assets/sass/page-content/breadcrumbs/_breadcrumb.scss
Removed padding from collapse targets.
=> Fixed collapse animation

gulp/build-tasks/assets-includes.js, gulp/build-tasks/modules.js, gulp/build-tasks/other-assets.js, gulp/build-tasks/template-pages.js, gulp/common-tasks/js.js, gulp/common-tasks/scss.js, gulp/gulp-config.js, gulp/release-tasks/scss-src.js, gulpfile.js, package.json
=> QOL-1893-fixed build and watch

src/assets/_project/_blocks/layout/header/_site-search.scss, src/assets/_project/_blocks/qg-main.js, src/assets/_project/_blocks/utils/qg-init.js
QOL-1758
- fixed search box styling on IE
- fixed accessibility issue
=> Qol 1758 fix search styling

package.json, src/assets/_project/_blocks/layout/section-nav/_section-nav.scss, src/assets/_project/_blocks/layout/section-nav/sample.html
QOL-1483 - nested navs styles added
=> QOL-1483 - added styles for subnavs

gulp/build-tasks/assets-includes.js, gulp/build-tasks/modules.js
QOL-2190
- fixed asset paths to point to static cdn
- fixed asset paths in docs to relative path
=> QOL-2190-fixed assets paths

gulp/build-tasks/node-docs-flatten.js, gulp/build-tasks/ssi-to-static.js, gulp/release-tasks/files.js, gulp/release-tasks/node-template-flatten.js, gulpfile.js, src/_other-files/release/readme.md, src/docs/assets/includes-local/section-nav/qg-web-template.html, src/docs/releases.html
From | To | Reason
-- | -- | --
template-cdn | template-cdn-ssi | This template contains ssi
template-cdn-static | template-cdn | This template is flat html
template-local | template-local-ssi | This template contains ssi
template-local-static | template-local | This template is flat html
=> Qol 2946 rename release folders

gulp/build-tasks/node-docs-flatten.js, gulp/build-tasks/ssi-to-static.js, src/docs/assets/includes-local/section-nav/qg-web-template.html, src/docs/releases.html
- created a page in docs to attach release notes written in confluence
=> QOL-2947-placeholder for uploading release notes

src/assets/_project/_blocks/components/social-media.js, src/assets/_project/_blocks/legacy/forms/_forms.scss, src/assets/_project/_blocks/legacy/forms/forms.js, src/assets/_project/_blocks/qg-main.js
Added SWE2 social media script
=> Cms 128 swe3 twitter feed

src/docs/components.html, src/docs/layout.html, src/docs/qg-utilities.html, src/docs/styles.html
SWE documentation updates - Dec 2018
=> SWE documentation updates - Dec 2018

src/assets/_project/_blocks/components/forms/qg-address-autocomplete.js
@AsifAmin Can you review? as this will need a bit of testing/peer review before release. The format address function will separate sub premise from address (plus write to fields), and keyup event (if location selection is not in progress) will take a copy of the first predicted result.
=> QOL 1754 Google autocomplete

src/assets/_project/_blocks/components/forms/qg-address-autocomplete.js
New pull request - had issues with conflicts.
=> QOL-1754 Updates to autocomplete tab enter controls

src/assets/_project/_blocks/components/forms/qg-address-autocomplete.js
=> QOL 1754 Autocomplete Tab + Enter

src/template-pages/aggregation-page.html
Adding alert to aggregation page template
=> QOL-3342 Adding alert to aggregation page template

src/assets/_project/_blocks/components/_misc.scss
Added grab component style to misc.scss
=> QOL-4213 Added grab component styles

package.json, src/assets/_project/_blocks/components/_alert.scss, src/assets/_project/_blocks/components/accordion/_accordion.scss, src/assets/_project/_blocks/components/accordion/accordion.js, src/assets/_project/_blocks/components/forms/qg-recaptcha.js, src/assets/_project/_blocks/components/forms/recaptcha.js, src/assets/_project/_blocks/components/forms/recaptcha/qg-global-feedback-recaptcha.js, src/assets/_project/_blocks/components/qg-components.js, src/assets/_project/_blocks/layout/footer/_site-footer.scss, src/assets/_project/_blocks/layout/footer/feedback-form.js, src/assets/_project/_blocks/layout/footer/footer-site-map-without-location.html, src/assets/_project/_blocks/layout/footer/footer-site-map.html, src/assets/_project/_blocks/layout/section-nav/_section-nav.scss, src/assets/_project/_blocks/layout/section-nav/section-nav.js, src/docs/components/accordion.html
This pull request contains changes for QOl-7818 accordion enhancements and QOL-7763
SWE4: Bug: Recaptcha should not be enabled on all pages until a form requests it
=> Qol 7818 accordion enhancements

src/assets/_project/_blocks/components/alerts/_qg-alert.scss, src/assets/_project/_blocks/layout/content/content-types/_call-out-box.scss, src/assets/_project/_blocks/utils/qg-misc.js
- reinstate i css support in fa icon in alert and callout box
- add warning to fellow developer
=> Qol 8453 reinstate back compatibility

src/assets/_project/_blocks/components/misc/_qg-images.scss, src/docs/components/images.html
rename class for backward compatibility
=> QOL- 8396 rename class for backward compatibility

src/assets/_project/_blocks/layout/location/qg-location.js
fix service finder search location bug
=> QOL-8593 fix qg-location

src/assets/_project/_blocks/components/banners/_qg-promotional-banner.scss
=> QOL-8615 unexpected padding in mobile service finder

src/assets/_project/_blocks/components/alerts/_qg-alert.scss
=> QOL-8630 fix unexpected alert padding

e2e/__tests__/components/twitter-feed-test.js, src/assets/_project/_blocks/components/banners/_qg-promotional-banner.scss
fix style for button alignment in .qg-promotional-banner__popular-apps
=> QOL-8616 fix unexpected alignment issue

src/assets/_project/_blocks/components/misc/_qg-cards.scss
fix an unexpected style error in qg-card introduced by QOL-8396
=> QOL-8396 update style

src/assets/_project/_blocks/layout/location/qg-location.js
to be released in 4.0.11 instead of 4.0.12
=> fix qg-location

src/assets/_project/_blocks/components/misc/_qg-images.scss
fix style bugs discovered in testing
=> QOL-8396 fix style bug

src/docs/components/images.html
=> QOL-8396 add GA data attr to image

src/assets/_project/_blocks/components/forms/qg-recaptcha.js, src/docs/captcha.html, src/docs/forms.html
Added doc and updated some functions
=> Qol 8398 new add recpatcha in swe components doc

src/assets/_project/_blocks/components/misc/_qg-images.scss, src/docs/components/images.html
this branch has been merged to 4.0.12 in this PR (https://github.com/qld-gov-au/qg-web-template/pull/441) but seems has been reverted
thus have to merge again
=> update image icon style

src/assets/_project/_blocks/layout/section-nav/_section-nav.scss
remove style on side bar title if it is not a link, otherwise same hover style as before
=> update style on .qg-section-nav

src/assets/_project/_blocks/components/banners/_qg-promotional-banner.scss, src/docs/examples/service-finder.html, src/template-pages/aggregation-page.html
fix padding styling issues
- update style on aggregation page promotional banner
- update examples in aggregation page and service finder page
=> fix banner tags spacing issue

src/assets/_project/_blocks/layout/_pagemodels/_aggregation.scss
fix gq-card style padding in mobile view
=> fix gq-card style

src/assets/_project/_blocks/layout/content/content-types/figure-credits-toggle.js
remove grace period from message
=> update deprecation message

src/assets/_project/_blocks/components/spinners/_qg-spinners.scss, src/assets/_project/_blocks/qg-main.scss, src/assets/_project/_blocks/scss-general/_qg-css-helpers.scss, src/assets/_project/_blocks/scss-general/_qg-css-variables.scss, src/assets/_project/_blocks/scss-general/_qg-global-variables.scss, src/assets/_project/_blocks/scss-general/bootstrap/_bootstrap-imports.scss, src/docs/components.html, src/docs/components/buttons.html, src/docs/components/spinners.html
main tasks
- add spinner component
- add spinner component documentation
- add loading variant in button component and documentation
secondary tasks
- add and expose css variables for theme color
- add and expose helper class for absolute center
=> Qol 9031 add spinner component

src/assets/_project/_blocks/components/misc/_qg-cards.scss
=> Qol 9076 fix card margin

.github/workflows/publish-chromatic.js.yml, .github/workflows/publish-storybook.js.yml
fix intermittent cicd error in Github Actions
=> Qol 9230 fix install issue

.github/workflows/publish-chromatic.js.yml, .github/workflows/publish-storybook.js.yml, .storybook/preview.js, .storybook/previewMainTemplate.ejs, package-lock.json, package.json
- fix script duplication in SSI template stories
- fix broken JS in non-SSI template stories
=> update storybook wrapper

src/assets/_project/_blocks/components/alerts/_qg-alert.scss, src/stories/components/Footer/Footer.stories.mdx, src/stories/components/Video/Video.stories.mdx
- modify css .global-alert hideon media print
- update footer story
=> Dc 33765 hide global alert on media print

src/assets/_project/_blocks/layout/header/_mobile-menu-button.scss, src/assets/_project/_blocks/layout/header/_site-nav.scss
- Mobile menu has a white background, so white text doesn't work
=> QOL-9431 fix menu text colour on mobile

src/assets/_project/_blocks/components/buttons/_qg-buttons.scss
- Should be navy blue not grey, see https://www.figma.com/file/Dn7V8WEiHBLPKoMNdItkEY/Simplify-UIKit-V0.4
=> [QOLDEV-47] fix global search button colour

src/assets/_project/_blocks/layout/content/_content.scss
- Landing page uses a non-standard structure, mostly outside the qg-primary-content container, so we need to apply rules to it separately
=> [QOLDEV-38][QOL-9487] apply standard styling to more links

src/assets/_project/_blocks/components/misc/_qg-cards.scss
- See https://www.figma.com/file/WpanghHaeTZgwGOJE2wnKT/QOL-8796---Hyperlinks
=> [QOLDEV-27] list item spacing should be 0.5em not 0

package.json, src/assets/_project/_blocks/components/buttons/_qg-buttons.scss, src/assets/_project/_blocks/components/link/_qg-link.scss, src/assets/_project/_blocks/layout/_pagemodels/_index.scss, src/assets/_project/_blocks/layout/asides/_asides.scss, src/assets/_project/_blocks/layout/banners/_qg-banner-blurb.scss, src/assets/_project/_blocks/layout/footer/_footer-feedback.scss, src/assets/_project/_blocks/layout/footer/_service-centre.scss, src/assets/_project/_blocks/scss-general/_qg-variables.scss, src/stories/components/Banner/templates/Default.html
- Apply underline rules to active/focus as well as hover
- Fix incorrect colouring of active banner links
- Refactor to extract more repeated behaviours to mix-ins
=> QOLDEV-34 QOLDEV-44 clean up link active states

src/assets/_project/_blocks/components/misc/_qg-cards.scss, src/assets/_project/_blocks/layout/content/_content.scss
- same behaviour as bulleted list
=> [QOLDEV-27] increase numbered list item spacing

src/assets/_project/_blocks/layout/content/_content.scss
- override Bootstrap default of 1rem, change to 0.75rem instead
=> [QOLDEV-55] reduce spacing after unordered lists

src/assets/_project/_blocks/components/quick-exit/_qg-quick-exit.scss
Replace the single text-decoration-line rule with the standard mixin.
=> [QOLDEV-46] apply standard styling to quick exit links

src/assets/_project/_blocks/components/buttons/_qg-buttons.scss, src/stories/components/Buttons/Buttons.stories.mdx, src/stories/components/Buttons/templates/Outline.html, src/stories/components/Buttons/templates/States.html
- Use mixin to apply 5px offset and 2px thickness on hover/active/focus
=> [QOLDEV-35] use standard underline thickness and offset for secondary buttons

src/assets/_project/_blocks/layout/_pagemodels/_index.scss
Figma designs have no underline
=> QOLDEV-29 remove underline from mobile menu buttons

src/assets/_project/_blocks/components/link/_qg-link.scss, src/assets/_project/_blocks/layout/breadcrumbs/_breadcrumbs.scss, src/assets/_project/_blocks/scss-general/_qg-variables.scss
Links on dark backgrounds shouldn't turn purple.
=> [QOLDEV-185] don't change colour of white links when visited

src/assets/_project/_blocks/components/misc/_qg-cards.scss, src/assets/_project/_blocks/scss-general/_qg-variables.scss
- ensure white cards get dark links
- ensure dark cards get white links
=> [QOLDEV-185] preserve correct link colours on cards

src/assets/_project/_blocks/layout/_pagemodels/_index.scss
- We only want to affect mobile links
=> [QOLDEV-29] revert change that will affect desktop index links

src/assets/_project/_blocks/components/link/_qg-link.scss, src/assets/_project/_blocks/components/misc/_qg-cards.scss, src/assets/_project/_blocks/layout/_pagemodels/_index.scss, src/assets/_project/_blocks/layout/breadcrumbs/_breadcrumbs.scss, src/assets/_project/_blocks/scss-general/_qg-variables.scss
=> QOLDEV-206 use underline for mobile index links on hover/focus/active

src/assets/_project/_blocks/components/link/_qg-link.scss, src/assets/_project/_blocks/legacy/forms/_forms.scss, src/assets/_project/_blocks/legacy/forms/_old_forms.scss
- Buttons should choose their own colour based on background colour
=> [QOLDEV-267] don't force button links to use black text

src/assets/_project/_blocks/components/link/_qg-link.scss
- Archive records search uses its own styling
=> [QOLDEV-263] exclude archive record search from link styling

src/assets/_project/_blocks/layout/section-nav/_section-nav.scss
- apply grey on hover/focus/active as per Figma design
=> [QOLDEV-199] fix background colour for section nav links

src/assets/_project/_blocks/components/forms/_qg-forms.scss, src/stories/components/Forms/templates/CheckboxStates.html, src/stories/components/Forms/templates/RadioStates.html
- Adjust border colour to match other form elements
- Add shadow on hover
=> QOLDEV-62 improve radio/checkbox styling

src/assets/_project/_blocks/components/buttons/_qg-buttons.scss, src/assets/_project/_blocks/scss-general/_qg-variables.scss
- Ensure that the 'hover' class is respected alongside the pseudo-class
- Simplify 'all-states' mixin to reduce boilerplate
=> [QOLDEV-259] fix hover colour for btn-secondary links

src/assets/_project/_blocks/layout/location/qg-location.js
ADMINAREANAME is now returned by ArcGIS in lowercase.
=> QOLDEV-270 fix location widget

src/assets/_project/_blocks/components/accordion/_qg-accordion.scss
- Replace manual rules with standard outline mixin
=> [QOLDEV-223] apply accordion outline on active state as well as focus

src/assets/_project/_blocks/components/buttons/_qg-buttons.scss, src/assets/_project/_blocks/components/link/_qg-link.scss, src/assets/_project/_blocks/layout/content/_content.scss, src/assets/_project/_blocks/legacy/forms/_forms.scss, src/assets/_project/_blocks/scss-general/_qg-variables.scss, src/stories/franchises/digital-dashboard/Dashboard.stories.mdx, src/stories/franchises/digital-dashboard/templates/Dashboard.html, src/stories/franchises/digital-dashboard/templates/Tenders.html
- Don't apply standard margins to elements that need to manage their own positioning
- Don't apply new styling to legacy buttons
=> QOLDEV-268 fix digital dashboard styling errors

src/assets/_project/_blocks/layout/location/qg-location.js
- Allow uppercase or lowercase attribute name
- Provide no-op callback function to Google Maps so we don't get a warning
=> QOLDEV-270 fix ArcGIS location lookup

src/assets/_project/_blocks/layout/header/_portal-links.scss, src/assets/_project/_blocks/layout/section-nav/_section-nav.scss
- Drop padding that is redundant with the standard link margin
=> [QOLDEV-268] fix margins in section nav heading

src/assets/_project/_blocks/components/link/_qg-link.scss, src/assets/_project/_blocks/layout/section-nav/_section-nav.scss
- ensure that section nav links use mixins properly to apply their underline colours
=> [QOLDEV-199] fix section nav underline colours

src/assets/_project/_blocks/components/link/_qg-link.scss
- Need to reapply this rule after implementing QOLDEV-261 since it increased the priority of the blue rule
=> [QOLDEV-41] don't apply default blue to visited links

src/assets/_project/_blocks/layout/_pagemodels/_index.scss
Make the on-focus outline for mobile index links cover the whole button.
=> QOLDEV-170 mobile index fixes

package.json, src/assets/_project/_blocks/components/link/_qg-link.scss, src/assets/_project/_blocks/layout/breadcrumbs/_breadcrumbs.scss, src/stories/franchises/Dfv/Dfv.stories.mdx, src/stories/franchises/Dfv/templates/LinksList.html
https://ssq-qol.atlassian.net/browse/QOLSVC-1031
Fixing 'Find out more' style at the bottom of https://oss-uat.clients.squiz.net/community/getting-support-health-social-issue/support-victims-abuse/domestic-family-violence/i-want-to-help-someone/how-do-i-talk-to-someone-about-their-domestic-violence-situation/support-someone-experiencing-domestic-and-family-violence
Also fixing the breadcrumb style which was done in https://ssq-qol.atlassian.net/browse/QOLDEV-285
=> Qolsvc 1031 dfv link color

.storybook/previewMainTemplate.ejs, src/assets/_project/_blocks/layout/head-assets-version-locked.html, src/assets/_project/_blocks/layout/head-assets.html, src/docs/examples/breadcrumb.html, src/docs/examples/cut-in.html, src/docs/examples/form-new-styles.html, src/docs/examples/formio.html, src/docs/examples/guide-page.html, src/docs/examples/index.html, src/docs/examples/recaptcha2.html, src/docs/examples/search-page.html, src/docs/examples/section-nav-example.html, src/docs/examples/service-finder.html
https://ssq-qol.atlassian.net/browse/QOLDEV-302
Derived from: https://ssq-qol.atlassian.net/browse/QOLSVC-433
If it isn't possible to zoom in, visitors with low vision may be unable to read your content.
According to WCAG, visitors should be allowed to increase text size from their browser to at least 200%.
WCAG 2.1: [Understanding Success Criterion 1.4.10: Reflow](https://www.w3.org/WAI/WCAG21/Understanding/reflow.html)
From https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-scale.html:
=> Qoldev 302 page zoom

src/assets/_project/_blocks/layout/footer/_site-footer.scss
https://ssq-qol.atlassian.net/browse/QOLDEV-307
Derived from: https://ssq-qol.atlassian.net/browse/QOLSVC-433
Based on site improve report:
=> QOLDEV-307 Increasing line-height in the footer to meet a11y guidelines

src/assets/_project/_blocks/components/misc/_qg-cards.scss, src/assets/_project/_blocks/scss-general/_qg-variables.scss
https://ssq-qol.atlassian.net/browse/QOLDEV-226
https://oss-uat.clients.squiz.net/forgov-dev/information-and-communication-technology/communication-and-publishing/website-and-digital-publishing/website-standards-guidelines-and-templates/swe/components/cards
Fixing card and outline border-radius.
=> QOLDEV-226 Improving clickable card focus

src/assets/_project/_blocks/components/quick-exit/_qg-quick-exit.scss, src/assets/_project/_blocks/layout/content/_content.scss, src/docs/components/quick-exit.html, src/stories/components/QuickExit/templates/Default.html
https://ssq-qol.atlassian.net/browse/QOLDEV-46
https://oss-uat.clients.squiz.net/forgov-dev/information-and-communication-technology/communication-and-publishing/website-and-digital-publishing/website-standards-guidelines-and-templates/swe/components/quick-exit
- Fixed hover, active and focus states
- Made help link and tooltip aligned
Some Squiz changes are needed as well to make it work. They are listed on the Jira ticket.
=> Qoldev 46 quick exit improvement

src/assets/_project/_blocks/components/buttons/_qg-buttons.scss, src/assets/_project/_blocks/scss-general/bootstrap/_variables.scss
https://ssq-qol.atlassian.net/browse/QOLDEV-35
https://oss-uat.clients.squiz.net/forgov-dev/information-and-communication-technology/communication-and-publishing/website-and-digital-publishing/website-standards-guidelines-and-templates/swe/components/buttons
From Bec:
Hover – border should change to black #313131 (like the text does).
Active – text colour shouldn’t change to white.
Removing the box-shadow and border-radius is done in https://github.com/qld-gov-au/qg-web-template/pull/855/files.
=> Qoldev 35 secondary btn states

package-lock.json, package.json
https://ssq-qol.atlassian.net/browse/QOLDEV-344
`npm install sass gulp-sass --save-dev`
=> QOLDEV-344 Upgrading sass

src/assets/_project/_blocks/layout/footer/footer-without-location.html, src/assets/_project/_blocks/layout/footer/footer.html, src/docs/examples/breadcrumb.html, src/docs/examples/cut-in.html, src/docs/examples/form-new-styles.html, src/docs/examples/formio.html, src/docs/examples/guide-page.html, src/docs/examples/index.html, src/docs/examples/recaptcha2.html, src/docs/examples/search-page.html, src/docs/examples/section-nav-example.html, src/docs/examples/service-finder.html
https://ssq-qol.atlassian.net/browse/QOLDEV-63
Improving heading hierarchy in the footer. This change only impacts the SWE template. The same change is applied to asset #118657 in UAT.
=> QOLDEV-63 Improving heading hierarchy in the footer

src/assets/_project/_blocks/layout/content/_content.scss
Adjusted margin's between paragraphs and unordered lists. CSS change under _content.scss
=> QOLDEV-55 added css rules to _content.scss

src/assets/_project/_blocks/components/link/_qg-link.scss, src/assets/_project/_blocks/layout/banners/_qg-banner-blurb.scss
https://oss-uat.clients.squiz.net/services/
- Fixed the blank buttons on mobile view
- Apply border-radius to buttons when active
=> Qoldev 363 service buttons

src/assets/_project/_blocks/components/buttons/_qg-buttons.scss, src/assets/_project/_blocks/layout/header/_header-location.scss, src/assets/_project/_blocks/layout/header/_site-nav.scss
- Applying standard button styles to btn-global-primary
- Applying margin zero to location link
- Fixing indenting on _site-nav.scss
https://oss-uat.clients.squiz.net/services/_nocache
**Before:**
Website search:
**After:**
=> Qoldev 366 fixing search and location margins

src/assets/_project/_blocks/components/link/_qg-link.scss, src/assets/_project/_blocks/layout/header/_header-location.scss, src/assets/_project/_blocks/scss-general/_qg-variables.scss
https://ssq-qol.atlassian.net/browse/QOLDEV-366
-  Fixing the location button's outline overlaps the text next to it.
- Moving margin-left: 0 from qg-button-outline-decoration mixin content to the argument.
**Before:**
**After:**
=> QOLDEV-366 Improving qg-link default margin and adjusting location button

src/assets/_project/_blocks/components/misc/_qg-cards.scss
https://oss-uat.clients.squiz.net/forgov-dev/information-and-communication-technology/communication-and-publishing/website-and-digital-publishing/website-standards-guidelines-and-templates/swe/components/cards
Applying border-radius to all-states so it does not get overridden.
=> QOLDEV-226 Applying border-radius to all states

src/assets/_project/_blocks/components/forms/_qg-forms-radio-check.scss
Deploy checked+label color fix prior to franchise UAT
=> QOLDEV 62 qg forms v2 radios

src/assets/_project/_blocks/layout/footer/_footer-feedback.scss
Set links in V1 Footer to be the correct colour.
=> QOLDEV-356 Fix for white links on V1 form

src/assets/_project/_blocks/layout/content/_content.scss
Change removes padding from select2 input fields
=> QOLDEV-55 select2 bugfix ul padding

src/assets/_project/_blocks/components/forms/_qg-forms-radio-check.scss
Adjusted scale of radio buttons to 0.625 (calculates to 20px) per SWE design spec
=> Qoldev 62 fix radio size

src/assets/_project/_blocks/layout/footer/footer-contact-us.html, src/docs/examples/index.html
This is to fix the repeated phone number in the google results.
=> QOLDEV-408 Updating thhe html for 13 QGOV phone number

src/assets/_project/_blocks/franchise/DFV/qg-dfv.scss, src/assets/_project/_blocks/layout/footer/_site-footer.scss, src/assets/_project/_blocks/qg-main.js, src/assets/_project/_blocks/scss-general/_qg-variables.scss, src/assets/_project/_blocks/scss-general/bootstrap/_bridge_bootstrap3.scss
Any page that has sensitive data has a Quick Exit Component. This is a good indication to identify if the links in a page need to be kept unchanged when visited.
https://oss-uat.clients.squiz.net/community/getting-support-health-social-issue/support-victims-abuse/domestic-family-violence/find-local-support
https://oss-uat.clients.squiz.net/community/getting-support-health-social-issue/support-victims-abuse/reporting-abuse
https://oss-uat.clients.squiz.net/community/women/support-for-women
https://oss-uat.clients.squiz.net/community/getting-support-health-social-issue/support-victims-abuse/sexual-abuse-assault/sexual-abuse-assault-getting-help
[About domestic and family violence and coercive control](https://oss-uat.clients.squiz.net/community/getting-support-health-social-issue/support-vic …
=> QOLDEV-414 Handling private links in any sensitive page

src/assets/_project/_blocks/components/misc/_qg-cards.scss
https://oss-uat.clients.squiz.net/
Before:
Applied zero margin to the links within the cards.
=> Qoldev 379 franchise cards

package.json
Incrementing version to 4.2.1 for PROD release
=> Increment version to 4.2.1 for PROD release

src/assets/_project/_blocks/layout/content/_content.scss, src/assets/_project/_blocks/utils/qg-misc.js
=> QOLDEV-425 Vertical alignment of social icons

src/assets/_project/_blocks/components/misc/_qg-cards.scss
Before:
https://www.forgov.qld.gov.au/news-events-and-consultation/news/choose-a-digital-career
After:
https://uat.forgov.qld.gov.au/news-events-and-consultation/news/choose-a-digital-career
=> QOLDEV-398 Light theme cards background

e2e/__tests__/layout/footer-feedback-test.js
Update click events on Footer feedback test to mimic real world browsers.
=> QOLDEV-488 Updated puppeteer script for footer feedback

src/assets/_project/_blocks/components/alerts/_qg-alert.scss, src/assets/_project/_blocks/layout/header/_site-search.scss
For featured results like 'registration' in the global search box
**Before:**
**After:**
=> Qoldev 451 search concierge button

src/assets/_project/_blocks/components/site-search/qg-site-search.scss
https://oss-uat.clients.squiz.net/search?query=renew+registration&num_ranks=10&tiers=off&collection=qld-gov&profile=qld&scope=&page=1&start_rank=1
Below issues are fixed in desktop and mobile view:
- Position of close/clear button position
- Long search terms run behind the search and close/clear buttons as they are positioned inside the input field.
=> QOLDEV-462 Improving search page

package-lock.json, package.json
SWE version was updated to 4.3 on a previous PR, however package-lock was not incremented.
This PR updates package-lock.
=> QOLDEV-26 SWE 4.3 increment package-lock file

src/assets/_project/_blocks/layout/banners/_qg-banner-blurb.scss
https://oss-uat.clients.squiz.net/dev/ghazal/test-banner/_nocache
https://oss-uat.clients.squiz.net/health/conditions/health-alerts/coronavirus-covid-19
Before:
After:
=> QOLDEV-352 Exluding dark blurb for white links

src/assets/_project/_blocks/components/misc/_qg-misc.scss
https://oss-uat.clients.squiz.net/transport/contacts/centres
Before:
After:
=> Qoldev 487 googlemaps marker label

src/assets/_project/_blocks/layout/banners/_qg-banner-blurb.scss
https://oss-uat.clients.squiz.net/health/conditions/health-alerts/coronavirus-covid-19
Applying standard SWE styles to the links within the banners in xs viewport.
=> Qoldev 352 blurb links in mobile

src/assets/_project/_blocks/components/tables/_tables.scss
Updating class name to `qg-table-no-stripes`
It's reference in Squiz design customisation needs to be updated as well.
=> QOLDEV-73 Updating class name to qg-table-no-stripes

src/assets/_project/_blocks/components/site-search/qg-funnelback-v16-refs.js
Formatting: replace double quotes with single
=> QOLDEV-518 double to single quotes

e2e/__tests__/components/funnelback-search-test.js
Expected results to search for 'jobs' are now:
- jobs in queensland government
- government jobs
- jobs volunteers
=> QOLDEV-515 Updating rexpected results from search for 'jobs'

src/assets/_project/_blocks/components/site-search/qg-site-search.js
This is to display the related services for search terms like seniors, rego.
=> Qoldev 515 funnelback filter results

package-lock.json
This is to resolve conflict in https://github.com/qld-gov-au/qg-web-template/pull/1080
=> Bumping babel/plugin-transform-runtime version

gulp/common-tasks/js-webpack.js, package-lock.json, package.json
Reverts qld-gov-au/qg-web-template#1112
=> Revert "Bump terser-webpack-plugin from 3.1.0 to 5.3.9"

package-lock.json, package.json
Reverts qld-gov-au/qg-web-template#1123
=> Revert "Bump @storybook/addon-links from 7.3.2 to 7.4.0"

package-lock.json, package.json
Reverts qld-gov-au/qg-web-template#1126
=> Revert "Bump @storybook/addon-mdx-gfm from 7.3.2 to 7.4.0"

package-lock.json, package.json
Reverts qld-gov-au/qg-web-template#1125
=> Revert "Bump storybook from 7.3.2 to 7.4.0"

package-lock.json, package.json
Reverts qld-gov-au/qg-web-template#1121
=> Revert "Bump @storybook/addon-actions from 7.3.2 to 7.4.0"

package-lock.json, package.json
Reverts qld-gov-au/qg-web-template#1127
=> Revert "Bump @storybook/addon-essentials from 7.3.2 to 7.4.0"

package-lock.json, package.json, src/assets/_project/_blocks/layout/banners/_qg-banner-blurb.scss
=> Qoldev 580 aligning button in service dropdown

package.json, src/assets/_project/_blocks/components/tables/_tables.scss
https://uat.forgov.qld.gov.au/information-and-communication-technology/communication-and-publishing/website-and-digital-publishing/website-standards-guidelines-and-templates/consistent-user-experience-standard/module-6-non-html-documents/module-6-checkpoint-6-file-types-and-sizes-in-links
https://uat.forgov.qld.gov.au/information-and-communication-technology/communication-and-publishing/website-and-digital-publishing/website-standards-guidelines-and-templates/swe/components/table/_nocache
**Before:**
**After:**
=> Qoldev 592 table top border

src/stories/components/Images/Images.stories.mdx, src/stories/components/Images/templates/FullWidth.html
Create a story for full-width image
=> QOLDEV-576 Create a story for full-width image

src/stories/components/Table/Table.stories.mdx, src/stories/components/Table/templates/Bordered.html
Adding a story for bordered table
=> QOLDEV-594 Adding a story for bordered table

src/stories/components/Images/templates/WithoutBorder.html
Fixing renamed class for image without border story
=> QOLDEV-578 Fixing class qg-unstyled for image without border

src/assets/_project/_blocks/components/quick-exit/_qg-quick-exit.scss
https://uat.forgov.qld.gov.au/employment-policy-career-and-wellbeing/health-safety-and-wellbeing/domestic-and-family-violence-support
Before:
=> QOLDEV-591 quick exit z-index

src/assets/_project/_blocks/components/site-search/qg-site-search.scss, src/assets/_project/_blocks/layout/header/_site-search.scss
=> QOLDEV-596 Search box clear button

.storybook/preview-head.html, .storybook/previewMainTemplate.ejs, src/assets/_project/_blocks/utils/qg-datatables.js, src/assets/_project/_blocks/utils/qg-datepicker.js
- adding crossorigin='anonymous'  for some css files to resolve warnings
- Fixing indenting lint error
=> QOLDEV-599 Lint error, and others

src/assets/_project/_blocks/components/misc/_qg-misc.scss, src/assets/_project/_blocks/layout/header/_portal-links.scss
https://uat.forgov.qld.gov.au/employment-policy-career-and-wellbeing/health-safety-and-wellbeing/domestic-and-family-violence-support
https://oss-uat.clients.squiz.net/
DFV pages have some negative top margin which is applied by a repo that Squiz manages, file global.scss.
=> QOLDEV-601 Making main navigation bar and DFV's seamless

src/assets/_project/_blocks/utils/qg-datatables.js
https://oss-uat.clients.squiz.net/_resources/matrix-documentation/components/searchable-and-sortable-table/_nocache
I had to update the js to make it work on FireFox.
=> Qoldev 569 sortable table for FireFox

src/assets/_project/_blocks/components/site-search/qg-site-search.scss, src/assets/_project/_blocks/layout/header/_site-search.scss
Improved the alignment of the icons and button in global search dropdown in mobile view.
**After:**
=> Qoldev 612 global search dropdown

readme/develop-in-storybook.md, src/stories/Introduction.mdx, src/stories/components/Forms/templates/Checkbox.html, src/stories/components/Forms/templates/Radio.html
Updated some of the attributes to be unique @stvp-qld . Also made some minor edits to Storybook intro content.
=> Edits to radio and checkbox examples in Storybook

package-lock.json, package.json
Reverts qld-gov-au/qg-web-template#1229
=> Revert "Bump @storybook/addon-mdx-gfm from 7.4.5 to 7.4.6"

src/assets/_project/_blocks/layout/header/_site-search.scss
Paragraph element within the service finder dropdown need left margin of 25px instead of 35px in small devices.
=> Qoldev 612 global search dropdown blurb

src/assets/_project/images/placeholders/README.md, src/docs/components/banner-blurb.html, src/docs/components/call-out-box.html, src/docs/components/cards.html, src/docs/components/carousel.html, src/docs/components/gallery.html, src/docs/components/images.html, src/docs/components/promotions.html, src/stories/assets/images/placeholders/README.md
Replacing references to via.placeholder.com with placehold.co
=> QOLDEV-534 Replacing via.placeholder.com with placehold.co

src/docs/components/quick-exit.html, src/stories/components/QuickExit/templates/Default.html
Updating the help text for quick exit component based on https://ssq-qol.atlassian.net/browse/QOLSVC-2497
This needs to be fixed in Squiz as well.
=> QOLDEV-635 Updating tooltip text for Quick Exit

src/assets/_project/_blocks/components/forms/_qg-forms.scss
**Examples:**
https://oss-uat.clients.squiz.net/law/assets/forms/formio-test/vaq/apply-for-financial-assistance
https://uat.forgov.qld.gov.au/sandbox/formio/form.io-test/employment-policy-career-and-wellbeing/flexible-work-agreement
Before:
=> QOLDEV-666 Styling formio dropdown items

src/assets/_project/_blocks/layout/content/options.html, src/assets/_project/_blocks/layout/footer/_site-footer.scss, src/assets/_project/_blocks/layout/footer/footer-contact-us.html, src/docs/examples/breadcrumb.html, src/docs/examples/cut-in.html, src/docs/examples/form-new-styles.html, src/docs/examples/formio.html, src/docs/examples/guide-page.html, src/docs/examples/recaptcha2.html, src/docs/examples/search-page.html, src/docs/examples/section-nav-example.html, src/docs/examples/service-finder.html, src/stories/components/SocialMedia/templates/Default.html
Twitter FontAwesome in footer is replaced with X twitter svg.
https://oss-uat.clients.squiz.net/contact-us
Also some storybook stories are updated to reflect the new svg as share icon.
=> QOLDEV-546 Updating twitter icon in the footer and other storybook docs

src/assets/_project/_blocks/layout/footer/_site-footer.scss
=> QOLDEV-546 X twitter icon adjustment in the footer

src/assets/_project/_blocks/components/carousel/_qg-carousel.scss, src/assets/_project/_blocks/layout/_pagemodels/_index.scss
Some more minor tweaks for index pages requested by our designers
- Spacing between the index items in mobile view
- carousel caption text color
- Adding extra padding before h1 on index pages
=> QOLDEV-668 Some more adjustment for index pages

src/assets/_project/_blocks/components/quick-exit/_qg-quick-exit.scss, src/docs/components/quick-exit.html, src/stories/components/QuickExit/templates/Default.html
https://oss-uat.clients.squiz.net/community/getting-support-health-social-issue/support-victims-abuse/domestic-family-violence
=> QOLDEV-635 Styling Quick Exit help text

src/assets/_project/_blocks/components/forms/_qg-forms.scss
https://oss-uat.clients.squiz.net/law/assets/forms/formio-test/vaq/apply-for-financial-assistance
(To get to this section select 'primary victim', then yes to all. For displaying datagrid answer yes to the questions under 'Other payments')
**Before:**
**After:**
This change will also make the dropdown's height similar to the dropdowns within datagrids.
=> QOLDEV-666 Styling form.ip dropdown

package-lock.json, src/assets/_project/_blocks/components/forms/_qg-forms.scss
Reverts qld-gov-au/qg-web-template#1487
.form-control.dropdown {
height: 44px;
}
was duplicated.
=> Revert "resolving conflicts"
